#数据库链接信息配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}


#mybatis的基础配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.itheima.pojo

#PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true